# Generated by Django 4.1.2 on 2022-10-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azubi_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzubiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='My_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Azubi',
        ),
        migrations.AddField(
            model_name='azubidata',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azubi_list.my_list'),
        ),
    ]
