# Generated by Django 4.1.2 on 2022-11-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azubi_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='Profession',
        ),
    ]
