# Generated by Django 4.1.2 on 2022-11-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azubi_list', '0002_rename_department_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='azubi',
            name='phone_number',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
