# Generated by Django 4.1.2 on 2022-10-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azubi_list', '0002_azubidata_my_list_delete_azubi_azubidata_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='azubidata',
            name='birthday',
            field=models.CharField(default='Leer', max_length=32),
        ),
    ]
