# Generated by Django 4.1.2 on 2022-10-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azubi_list', '0003_azubidata_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='azubidata',
            name='phone_number',
            field=models.CharField(default='Leer', max_length=32),
        ),
    ]
