# Generated by Django 4.1.2 on 2022-11-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azubi_list', '0003_azubi_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azubi',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
