# Generated by Django 4.1.2 on 2022-11-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azubi_list', '0004_alter_azubi_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azubi',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
