# Generated by Django 4.1.2 on 2023-01-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azubi_list', '0004_alter_azubi_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('changed', models.IntegerField()),
            ],
        ),
    ]
