# Generated by Django 4.1.2 on 2023-01-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azubi_list', '0005_daycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='azubi',
            name='PLZ',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='azubi',
            name='address',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
