# Generated by Django 4.1.2 on 2023-01-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azubi_list', '0006_azubi_plz_azubi_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azubi',
            name='PLZ',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='azubi',
            name='address',
            field=models.CharField(max_length=30),
        ),
    ]
